spring.application.name=Wijha

spring.datasource.url=jdbc:mysql://localhost:3306/Wijha_DB

spring.datasource.username=root
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true

spring.jpa.generate-ddl=true

spring.jpa.hibernate.ddl-auto=create-drop

spring.web.error.include-message=always

spring.web.error.include-stacktrace=always

jwt.secret=jbZ2itxd2vZ3jE0AgEGcVxPatwkKHBpzovDKHKNGYiu